language: cpp
os: osx
osx_image: xcode7.3
before_install:
    - curl -L -O http://netcologne.dl.sourceforge.net/project/boost/boost/1.55.0/boost_1_55_0.tar.gz
    - tar xzf boost_1_55_0.tar.gz -C thirdparty/boost/
    - brew update
    - brew install glew lz4 libjpeg libpng lzo pkg-config libusb
    - brew install qt5
    - chmod -R a+rX /usr/local/opt/qt5/
    - find /usr/local/opt/qt5/ -type d -print0 | gzip | base64 || true
script:
    - pushd thirdparty/tiff-4.0.3 && ./configure && make && popd
    - mkdir toonz/build && cd toonz/build
    - CMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake cmake ../sources
    - make
