language: cpp
os: osx
osx_image: xcode7.3

env:
  global:
    # Coverity Scan environment
    - COVERITY_SCAN_PROJECT_NAME="janisozaur/opentoonz"
    - COVERITY_SCAN_NOTIFICATION_EMAIL="janisozaur+opentoonz@gmail.com"
    - COVERITY_SCAN_BRANCH_PATTERN="coverity-2"
    - COVERITY_SCAN_BUILD_COMMAND="make -j2"
    - COVERITY_SCAN_BUILD_URL="https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh"
    - COVERITY_SCAN_BUILD="curl -s $COVERITY_SCAN_BUILD_URL | bash"
    - secure: "S77aAnr26eW+jpt2UV4NMkYL47BMSeeo9iSLOI3ByjgmLKHvSSJUqC22OJbio3/dEdgkVhvEQn3fLM/QTMKBUgGTI5MSB0kYVhAY1vM1nSr2/QiDsZcUpBZ0UG78BLAgaB0Z52r/0FOFejS3PRVLVzXCIwp4tqyqZFPy5E5f23oTY33GmypldfBYUeBK4F8WfaF3HgOtZT4OMgfs2qdr27crkjbbh+4S2BEyMzYt3oadj8PVsvSrNdvHJoSnaeMUQ2ACGN6t7uQQizjjN/944FydTP+sbV6+T5BkRXj53NnFJVVmZE3B2hT9SSkcmDllV19DGmwzSRxu+zJTuFnuMbNNtiS/v8+h5jf9NUlj1fzK6LT41HequHzWaP29CYBdmUh/dxRek+b95i5SeRAsVTFWXDTj1UVF0p8FkUVFS+lb/T9Tz4Xny5ZAP4TLZDeGQ8blumeDKG0MxfhjomPMhvcDh//Mf7wmvmxYPdGF0MI0ziytp5R7ZViAtlOB0VZB2Zu7RJir0ft1p43Q7w/PWuBTPCpkPb9riuUTau7Syyy0jCmjSnMYcl/T+NU3OTiIaRPcvpi4Z4efKotCiTjFmZ+S5DBj+S4h6aWBDxjEPc/fjLbztAyykntjD3ZZFkrHnDmqPrNcrpAFTVXh1n0qi+PNFwoIW7JU0W43UAagioc="

before_install:
    - brew update
    - brew install glew lz4 libjpeg libpng lzo pkg-config libusb
    - brew install qt5
    - chmod -R a+rX /usr/local/opt/qt5/

before_script:
    - pushd thirdparty/tiff-4.0.3 && ./configure && make && popd
    - mkdir toonz/build && cd toonz/build
    - CMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake cmake ../sources

script:
    - echo $COVERITY_SCAN_BUILD
    - $COVERITY_SCAN_BUILD
