version: 0.0.1.{build}
os: Visual Studio 2015
build_script:
    - cmd:
        >-
        move thirdparty/LibJPEG/jpeg-9/jconfig.vc thirdparty/LibJPEG/jpeg-9/jconfig.h

        move thirdparty/tiff-4.0.3/libtiff/tif_config.vc.h thirdparty/tiff-4.0.3/libtiff/tif_config.h

        move thirdparty/tiff-4.0.3/libtiff/tiffconf.vc.h thirdparty/tiff-4.0.3/libtiff/tiffconf.h

        move thirdparty/libpng-1.6.21/scripts/pnglibconf.h.prebuilt thirdparty/libpng-1.6.21/pnglibconf.h

        mkdir toonz/build

        cd toonz/build

        set QT_DIR="C:\Qt\5.6\msvc2015"

        cmake ../sources

        msbuild /p:Configuration=Release OpenToonz.sln /v:Minimal
